### ISSUE TITLE
Subscription.save() raises HTTP 400 error

### ISSUE THREAD

**Issue by litleleprikon** [moira-alert/python-moira-client#12]
When calling save method on subscription library raises the HTTPError: 400 Bad request

```Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/emilsharifullin/Documents/projects/kontur/moira/python-moira-client/moira_client/models/subscription.py", line 168, in save
    self._send_request()
  File "/Users/emilsharifullin/Documents/projects/kontur/moira/python-moira-client/moira_client/models/subscription.py", line 94, in _send_request
    result = self._client.put('subscription', json=data)
  File "/Users/emilsharifullin/Documents/projects/kontur/moira/python-moira-client/moira_client/client.py", line 98, in put
    r.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:8081/api/v1/namespaces/moira-alert/services/http:moira-api:8081/proxy/api/subscription```

**Comment by androndo** [comment]
I checked two scenarios:
* create from [readme example](https://github.com/moira-alert/python-moira-client#create-subscription)
* update: fetch, change something, save.

Both passed normal, 400 raises only on missing or empty required fileds (contacts or tags).

So I think we can close this issue as **non-repeatable**.

#### System info:
* Python 3.8.5
